// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"
#include "main.hpp"

// tests for exercise 1
TEST_CASE("Test1 ", "[Test 1]")
{
	string filename;
	int N;
	filename = "employee.txt";
	N = writeFile(filename);
	REQUIRE(N == 3);
	N = readFile(filename);
	REQUIRE(N == 3);
}